language: ruby
script: rake spec:travis
before_script:
  - travis_retry rake spec:travis:deps
  - travis_retry rake man:build
  - travis_retry rake spec:rubygems:clone_rubygems_$RGV

rvm:
#  - 2.3.1
#  - 2.2
#  - 2.1
#  - 2.0.0
#  - 1.9.3
#  - 1.8.7
  - jruby-9.1.6.0

# Rubygems versions MUST be available as rake tasks
# see Rakefile:125 for the list of possible RGV values
env:
  # We need to know if changes to rubygems will break bundler on release
#  - RGV=master
  # Test the latest rubygems release with all of our supported rubies
  - RGV=v2.6.8

matrix:
  include:
    - rvm: jruby-9.1.6.0
      env:
        - RGV=v2.6.8 JRUBY_OPTS="-J-Djruby.launch.inproc=true"
